### ISSUE TITLE
feature requests

### ISSUE THREAD

**Issue by alzayats** [mgwillia/implicit-inpainting-pytorch#1]
Hi,
Thanks for the repo.
Would you mind add a readme ?

**Comment by mgwillia** [comment]
Hi, I had forgotten this was public. I will certainly add a readme, but possibly not until CVPR concludes. Would you mind sharing what you would like to see in the readme, I can make sure to include that. Also, I will double check my implementation to make sure this was the working version.

**Comment by alzayats** [comment]
No worries ;) 

I would like to see this in the readme:
Requirements
Data
Training
Evaluation

Thanks for your quick response.
